# Package Installation

In [ ]:

!pip install sentence-transformers
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 34.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 21.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 6.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 50.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

# Encode docs using sentence-transformer

Sentence Transformers provides open source models to enable encoding of text data. So you can either use this model or you can use embedding models of openai in the coming sections. Do not forget, the models in sentence transformers are free but not openai.

In [ ]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer('multi-qa-mpnet-base-dot-v1')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/8.71k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
data = [
    'Hayat nasıl gidiyor diyenlere aslında süper gidiyor Elhamdülillah',
    'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
]
encoded_data = encoder.encode(data)

The code snippet above includes two sentence in Turkish as an example. You can add or modify there to have different cases.

# Find in PDF

If you want to encode PDF you can run this snippet. If you don't want, skip this part.

In [ ]:
import io
import pandas as pd
from google.colab import files
print("Choose a single file")
uploaded = files.upload()

Choose a single file


Saving Prompt-Engineering-Lecture-Elvis.pdf to Prompt-Engineering-Lecture-Elvis.pdf


In [ ]:
!pip install PyPDF2

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 12.4 MB/s eta 0:00:00


In [ ]:
from PyPDF2 import PdfReader

# set path to your pdf
reader = PdfReader('/content/Prompt-Engineering-Lecture-Elvis.pdf')

# printing number of pages in pdf file
print(len(reader.pages))
allText =[]
for page in reader.pages:
# split page sentences with '.' character to split them one by one
    for text in page.extract_text().split('.'):
        if len(text)>0:
            allText.append(text)
print(allText)

50
['Elvis SaraviaPrompt EngineeringA lecture by DAIR', 'AI', 'Prerequisites & Objectives•Prerequisites: •Python •Knowledge of language models •Basic understanding of deep learning / ML concepts •Objectives •Present an introduction to prompt engineering •Present an overview of the latest prompting techniques  •Provide demonstrations and exercises to practice different prompting techniques', 'Agenda•Introduction to Prompt Engineering •Advanced Techniques for Prompt Engineering •Applications & Tools •Conclusion & Future Directions', 'Introduction to Prompt EngineeringPart 1', 'What are prompts?•Prompts involve instructions and context passed to a language model to achieve a desired task •Prompt engineering is the practice of developing and optimizing prompts to efficiently use language models (LMs) for a variety of applications  •Prompt engineering is a useful skill for AI engineers and researchers to improve and efficiently use language modelsWhat is prompt engineering?Prompt engineerin

# Encode using openai

If you want to use openai embedding models to encode your data you can use this section.

In [ ]:

%%capture
!pip install openai

In [ ]:
import openai
import os

openai.api_key = "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"

#openai.Engine.list()  # check we have authenticated

In [ ]:

def encode_open(input):
# you can change model if you want different
    MODEL = "text-embedding-ada-002"
    res = openai.Embedding.create(
       input=input, engine=MODEL
    )
    embeds = [record['embedding'] for record in res['data']]
    import torch
    embeds=torch.FloatTensor(embeds)
    return embeds

In [ ]:
def encode_open(input):
    # you can change model if you want different
    MODEL = "text-embedding-ada-002"
    # Use openai.embeddings_utils.embeddings_with_model instead of openai.Embedding.create
    res = openai.embeddings_utils.embeddings_with_model(
        input=input, model=MODEL  # Use model instead of engine
    )
    # res is now a dictionary containing 'data' with the embeddings
    embeds = res['data'][0]['embedding']  # Access the embedding directly
    import torch
    embeds = torch.FloatTensor(embeds)
    return embeds

If you want to use PDF for encoding you can run the two code snippets below.

In [ ]:
allText

['Elvis SaraviaPrompt EngineeringA lecture by DAIR',
 'AI',
 'Prerequisites & Objectives•Prerequisites: •Python •Knowledge of language models •Basic understanding of deep learning / ML concepts •Objectives •Present an introduction to prompt engineering •Present an overview of the latest prompting techniques  •Provide demonstrations and exercises to practice different prompting techniques',
 'Agenda•Introduction to Prompt Engineering •Advanced Techniques for Prompt Engineering •Applications & Tools •Conclusion & Future Directions',
 'Introduction to Prompt EngineeringPart 1',
 'What are prompts?•Prompts involve instructions and context passed to a language model to achieve a desired task •Prompt engineering is the practice of developing and optimizing prompts to efficiently use language models (LMs) for a variety of applications  •Prompt engineering is a useful skill for AI engineers and researchers to improve and efficiently use language modelsWhat is prompt engineering?Prompt engineer

In [ ]:
input=['Hayat nasıl gidiyor diyenlere aslında süper gidiyor Elhamdülillah','Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi']
encoded_data=encode_open(input)

In [ ]:
!pip install --upgrade openai

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 571.1/571.1 kB 29.1 MB/s eta 0:00:00
  Attempting uninstall: openai
    Found existing installation: openai 1.61.1
    Uninstalling openai-1.61.1:
      Successfully uninstalled openai-1.61.1


In [ ]:
import openai

def encode_open(input):
    # you can change model if you want different
    MODEL = "text-embedding-ada-002"

    # For openai versions >= 0.27.0:
    res = openai.Embedding.create(input=input, model=MODEL)
    embeds = [record['embedding'] for record in res['data']]

    import torch
    embeds=torch.FloatTensor(embeds)
    return embeds

# Add to index

We will add the encoded texts into the FAISS(semantic search similarity library) inshaAllah. So the text data will be add into the database.

In [ ]:

d=encoded_data.shape[1]
d

768

In [ ]:
import faiss
import numpy as np

# IndexFlatIP: Flat inner product (for small datasets)
# IndexIDMap: store document ids in the index as well
index = faiss.IndexIDMap(faiss.IndexFlatIP(d))
index.add_with_ids(encoded_data, np.arange(encoded_data.shape[0]))

# Search for question

You can search your text using the functions below, if you use openai, run search_openai function.

In [ ]:
def search(query, k=7):
    query_vector = encoder.encode([query])
    top_k = index.search(query_vector, k)
    print(top_k)
    return [
        input[_id] for _id in top_k[1][0]
    ]

search("hayat iyi gidiyor mu")

(array([[ 2.7926863e+01,  1.9817183e+01, -3.4028235e+38, -3.4028235e+38,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]], dtype=float32), array([[ 0,  1, -1, -1, -1, -1, -1]]))


['Hayat nasıl gidiyor diyenlere aslında süper gidiyor Elhamdülillah',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi']

In [ ]:
def search_pdf(query, k=7):
    query_vector = encoder.encode([query])
    top_k = index.search(query_vector, k)
    print(top_k)
    return [
        allText[_id] for _id in top_k[1][0]
    ]

search_pdf("hayat iyi gidiyor mu")

(array([[ 2.7926863e+01,  1.9817183e+01, -3.4028235e+38, -3.4028235e+38,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]], dtype=float32), array([[ 0,  1, -1, -1, -1, -1, -1]]))


['Elvis SaraviaPrompt EngineeringA lecture by DAIR',
 'AI',
 'com/dair-ai/Prompt-Engineering-Guide',
 'com/dair-ai/Prompt-Engineering-Guide',
 'com/dair-ai/Prompt-Engineering-Guide',
 'com/dair-ai/Prompt-Engineering-Guide',
 'com/dair-ai/Prompt-Engineering-Guide']

In [ ]:
import openai

def encode_open(input):
    # you can change model if you want different
    MODEL = "text-embedding-ada-002"

    # For openai versions >= 0.27.0, but less than 1.0.0:
    # res = openai.Embedding.create(input=input, model=MODEL)
    # embeds = [record['embedding'] for record in res['data']]

    # For openai versions >= 1.0.0:
    res = openai.embeddings_utils.get_embeddings(input, model=MODEL)
    # Use get_embeddings and pass input directly
    embeds = res
    # embeds is already a list, no need to extract it

    import torch
    embeds = torch.FloatTensor(embeds)
    return embeds

In [ ]:
!pip install --upgrade openai

import openai

def encode_open(input):
    # you can change model if you want different
    MODEL = "text-embedding-ada-002"

    # For openai versions >= 0.27.0:
    res = openai.Embedding.create(input=input, model=MODEL)
    embeds = [record['embedding'] for record in res['data']]



# Save encoded texts

İf you want to save the encoded texts, you can use the cell below.

In [ ]:
path = './faiss.index'

# Save index
faiss.write_index(index, path)

# Load encoded texts

You can load back the encoded texts providing the path of index.

In [ ]:
index = faiss.read_index(path)
search("hayat iyi gidiyor mu")

(array([[ 2.7926863e+01,  1.9817183e+01, -3.4028235e+38, -3.4028235e+38,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]], dtype=float32), array([[ 0,  1, -1, -1, -1, -1, -1]]))


['Hayat nasıl gidiyor diyenlere aslında süper gidiyor Elhamdülillah',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi',
 'Silahlar savaş için oldukça gereklidir. Çünkü hayat memat meselesi']